# Generated by Django 3.0.6 on 2020-05-31 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminManager', '0001_initial'),
        ('hiringManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=30, unique=True)),
                ('sequence_number', models.IntegerField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=68, unique=True, verbose_name='email')),
                ('app_name', models.CharField(max_length=30)),
                ('date_of_registration', models.DateTimeField(auto_now_add=True, verbose_name='registraiton joined')),
                ('is_active', models.BooleanField(default=True)),
                ('yrs_of_exp', models.IntegerField(max_length=10)),
                ('is_hired', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('hire_status', models.CharField(default='Yet to be decided', max_length=30)),
                ('complete_status', models.CharField(default='Not yet started', max_length=30)),
                ('vac_id', models.IntegerField(default=None, max_length=10)),
                ('ind_vac_id', models.IntegerField(default=None, max_length=10)),
                ('current_level', models.CharField(default=None, max_length=30)),
                ('preffered_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminManager.JobLocation')),
                ('skills', models.ManyToManyField(to='hiringManager.MasterSkill')),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hiringManager.IndividualVacancies')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateTimeField(auto_now_add=True, verbose_name='interview date ')),
                ('result', models.CharField(max_length=20)),
                ('is_passed', models.BooleanField(default=False)),
                ('comments', models.CharField(max_length=100)),
                ('app_id', models.IntegerField(max_length=10)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talentManager.MasterApplicant')),
                ('interview_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talentManager.InterviewLevel')),
            ],
        ),
    ]
