# Generated by Django 3.0.6 on 2020-06-11 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManager', '0003_auto_20200611_1614'),
        ('talentManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterapplicant',
            old_name='vacancy',
            new_name='individual_vacancy',
        ),
        migrations.AddField(
            model_name='masterapplicant',
            name='master_vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hiringManager.MasterVacancy'),
        ),
    ]
