# Generated by Django 3.0.6 on 2020-06-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentManager', '0002_auto_20200611_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterapplicant',
            name='current_level',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='masterapplicant',
            name='ind_vac_id',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='masterapplicant',
            name='vac_id',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
