# Generated by Django 3.0.6 on 2020-06-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentManager', '0004_masterapplicant_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewhistory',
            name='app_id',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
