# Generated by Django 3.0.6 on 2020-06-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentManager', '0005_auto_20200613_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterapplicant',
            name='current_level',
            field=models.CharField(default='', max_length=30),
        ),
    ]
