# Generated by Django 3.0.6 on 2020-05-31 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vac_name', models.CharField(max_length=30)),
                ('date_of_posting', models.DateTimeField(auto_now_add=True, verbose_name='posting date')),
                ('vac_designation', models.CharField(max_length=100)),
                ('no_of_vacancies', models.IntegerField(max_length=10)),
                ('project_name', models.CharField(max_length=50)),
                ('yrs_of_exp', models.IntegerField(max_length=10)),
                ('comments', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('hiringManager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminManager.MasterEmployee')),
                ('job_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminManager.JobLocation')),
                ('skills', models.ManyToManyField(to='hiringManager.MasterSkill')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualVacancies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vac_name', models.CharField(max_length=30)),
                ('date_of_posting', models.DateTimeField(auto_now_add=True, verbose_name='posting date')),
                ('app_designation', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=50)),
                ('yrs_of_exp', models.IntegerField(max_length=10)),
                ('comments', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('master_vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiringManager.MasterVacancy')),
                ('preffered_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminManager.JobLocation')),
            ],
        ),
    ]
