# Generated by Django 3.0.6 on 2020-06-11 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hiringManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualvacancies',
            old_name='app_designation',
            new_name='vac_designation',
        ),
        migrations.AddField(
            model_name='individualvacancies',
            name='hiringManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualvacancies',
            name='ind_vac_count',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='individualvacancies',
            name='skills',
            field=models.ManyToManyField(to='hiringManager.MasterSkill'),
        ),
    ]
