# Generated by Django 3.0.6 on 2020-06-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManager', '0002_auto_20200611_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualvacancies',
            old_name='preffered_location',
            new_name='vac_location',
        ),
    ]
