# Generated by Django 3.0.6 on 2020-06-11 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManager', '0003_auto_20200611_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mastervacancy',
            old_name='job_location',
            new_name='vac_location',
        ),
    ]
