# Generated by Django 3.0.6 on 2020-06-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManager', '0004_auto_20200611_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualvacancies',
            name='status',
            field=models.CharField(default='Not yet started', max_length=30),
        ),
        migrations.AddField(
            model_name='mastervacancy',
            name='status',
            field=models.CharField(default='Not yet started', max_length=30),
        ),
    ]
