# Generated by Django 3.0.6 on 2020-06-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManager', '0005_auto_20200614_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterskill',
            name='skill_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
